/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "Elrey_api": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "Elrey_fotos": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "Elrey_jwt_secreto": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Elrey_pin": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Elrey_proveedores": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Elrey_radar": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}